stages:
  - build
  - test

image: luizperes/parabix:llvm-6.0.1

build_llvm6:
  stage: build
  except: [merge_requests]
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4

test_llvm6:
  stage: test
  script:
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j4 check && make kernel-tests

